### ISSUE TITLE
ThreeJS vs. Verge + obfuscated encoding?

### ISSUE THREAD

**Issue by X-Equals-Zero** [Soft8Soft/verge3d#1]
Your library appears to be a direct copy of a popular JS webGL framework, ThreeJS

Just 1 example from ThreeJS examples: https://github.com/mrdoob/three.js/blob/master/examples/webgl_instancing_raycast.html

Your code at https://github.com/Soft8Soft/verge3d-code-examples/blob/master/webgl_instancing_raycast.html:

ThreeJS license agreement has some stipulations here (https://github.com/mrdoob/three.js/blob/dev/LICENSE)

not sure what "keymanager.py" does
For instance, what is the activate function writing?

```
def activate(path, key, l1ll_opy_=True):
    if l1ll_opy_ and not l111l_opy_(key):
        return False
    l1ll1_opy_ = l1_opy_ (u"ࠨࡡࡢ࡚࠸ࡊࡌࡠࡡࠪࠄ") + key[0:10]
    file = None
    with open(path, l1_opy_ (u"ࠩࡵࠫࠅ"),  encoding=l1_opy_ (u"ࠪࡹࡹ࡬࠭࠹ࠩࠆ")) as l1llll_opy_:
        file = l1llll_opy_.read()
    with open(path, l1_opy_ (u"ࠫࡼ࠭ࠇ"),  encoding=l1_opy_ (u"ࠬࡻࡴࡧ࠯࠻ࠫࠈ")) as l1l1l_opy_:
        l1l1l_opy_.write(l1lll_opy_.sub(l1ll1_opy_, file))
    return True
```

What is the point of this library?

**Comment by alexkowel** [comment]
Hi,

Please consider this my personal opinion. I'm working in Verge3D team since 2017. I don't think I'd earn my salary during these years for just copy-pasting and changing "Three.js" to "Verge3D" everywhere in the code.

Verge takes many things from Three.js, as well as dozen other open-source libraries, but adds many things too, so we consider it an original product! BTW we pay credit to the authors in the EULA, as required by MIT and other licenses. This is not something invented by us. You might try reading the licensing section in your Apple or Android device and see similar stuff there (iOS is based on FreeBSD, Android is pure Linux).

As for the keymanager.py, it does nothing serious, just removes the watermarks in v3d.js builds. We got many customers paying for Verge3D, so crippling their systems would be really bad for business. Hope this makes sense.

**Comment by X-Equals-Zero** [comment]
Thanks for your clarification! Someone posted this in a programming discord so I thought I should get to the bottom of it! I myself have fallen victim to library phishing, so at first glance and after I checked the license agreement, I saw no MIT license (which is offsite and hidden down below in your EULA on a separate link) but I can understand why you keep it separate as to not confuse customers about your terms. 

Best of luck!
